---
title: "Preregistration Summary for 'Quantifying Change: Challenges and Strategies in Effect Size Determination for Exercise Intervention Meta-Analyses'"
author: "Simon Nolte"
date: today
format: 
  pdf:
    link-citations: true
mainfont: Arial
bibliography: ../references.bib
csl: ../apa.csl
---

*This document will be published on the Open Science Framework under a [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/) license. It is accompanied by a more detailed preregistration that follows the 'Inclusive Systematic Review Registration Form' [@vandenakker2023].*

------------------------------------------------------------------------

Systematic meta-analyses are considered the best available level of scientific evidence in exercise science informing research and practice. However, in order to provide reliable information the underlying analyses have to adhere to current standards for meta-analyses (e.g. PRISMA). Therefore, it is highly problematic that increasingly methodological flaws are often reported [@kadlec2023; @hill2023]. However, systematic analyses about the prevalence of methodological flaws in exercise science meta-analyses are scarce at present [@kadlec2023].

Studies in exercise science often follow a randomized controlled trial design where in the simplest case participants are randomized into either a control or a treatment arm. In most studies, the main variable of interest is measured before and after treatment. Therefore one important methodological aspect of meta-analyses in exercise science studies is related to the choice of the effect size calculation strategy. In principle, there are several potential choices possible: effect sizes based on change scores, effect sizes based on post-measurement scores, and effect sizes based on post-measurement score that adjust for individual pre-measurement scores (i.e., ANCOVA approaches). These methods differ in their statistical power, model assumptions, and the data required from the original studies included in the meta-analysis. Crucially, many of these methods rely on data imputation when data of the original studies is incompletely reported. At present no systematic analysis about the application of different effect size measures in exercise science meta-analyses and their effects on meta-analyses outcomes is available.

The present project will therefore review the effect size calculation methods used in exercise intervention meta-analyses published in high-ranked journals in the year 2024 to map current practices and compare them to published recommendations. Further, a case study will be presented to demonstrate the impact of different effect size calculation methods on meta-analysis outcomes. Based on the current state of effect size choices in meta-analysis in exercise science the project will derive recommendations to select appropriate effect size calculation methods and parameters based on the specific research goal.

For the systematic review of published literature, a database search for all articles containing the phrase “meta-analysis” in their title, published in 2024, in journals which published the 20 most-cited meta-analyses in the field according to @kadlec2023. Screening of articles will be performed in two stages: blinded abstract screening and non-blinded full-text screening. Articles that do not include at least one meta-analysis of an exercise intervention in a two-group pre-post design will be excluded. Meta-analyses of other research designs require their own methods of effect size calculation but we believe these are less common in exercise science and thus not the focus of this project. Two independent researchers will conduct the screening. In cases of disagreement on exclusion decisions, a third independent researcher will resolve the conflict. If fewer than 100 articles remain after screening, we will extend the search range by including articles published in the preceding year(s) until the threshold is met.

Data extraction will be performed in three stages: First, a researcher extracts the reported effect size calculation method and related parameters from the meta-analysis. Second, the same researcher determines the used effect size calculation method by recalculating a single randomly selected study-level effect size measure from the meta-analysis. With this procedure we aim to verify the actually used method without needing to rely only on the reporting of the article and without having to recalculate every single effect size for all studies included. Third, an independent researcher checks the extracted data items for their correctness (validation). If the independent researcher decides not to approve the initial data extraction, the first extractor must revise the extraction based on the validation comments until it is successfully validated. We include an additional reliability test by performing the first 20 data extractions by two independent extractors.

The primary outcome of the review is the frequency of methods actually used for effect size calculation in exercise science meta-analyses, along with their imputation parameters, if applicable. Secondary outcomes are the reported effect size calculation methods, the justification provided for the chosen method, and the addressing of baseline imbalances (e.g., whether the meta-analysis only including randomized controlled trials, or systematically assessed randomization bias).

We will describe the proportion (along with its 95%-confidence interval) of specific methods used for effect size determination. Additionally, we will calculate the percentage of studies with correct, incomplete, incorrect, or missing reporting of their methods. Reporting is defined as correct if the exact methods described lead to a successful recalculation of an individual effect size; incomplete means that further assumptions (about parameters and/or calculation methods) lead to a successful recalculation; incorrect if a recalculation given the reported methods is not possible; missing if no information on the used methods is given. The justifications provided for the chosen methods will be qualitatively assessed.

To investigate the influence of effect size measure choices on meta-analysis outcomes we will perform a case study: We will reanalyze the meta-analysis by @oliveira2024, specifically their main finding that endurance exercise interventions with a polarized training intensity distribution result in greater improvements in maximum oxygen uptake compared to interventions with other intensity distributions. Our reanalysis will focus on the underlying meta-analysis of this finding (Fig. 4 in @oliveira2024), after correcting for double- or triple-counting of studies. We chose this study because it matches our inclusion criteria and stands exemplary for meta-analyses of exercise interventions with a two-group pre-post design.

We will apply different methods for effect size calculation, including ANCOVA, change scores, and post scores. For the ANCOVA and change score methods, we will contact the authors of the original studies to obtain missing individual participant data and/or summary measures. For the change score method, we will use different approaches to imputing the standard deviation of change scores, using both fixed imputation parameters and informed parameters. The informed parameters will be derived from a other studies on changes in maximum oxygen update following exercise interventions, which allow for the recalculation of pre-post correlations [@renwick2024; @rosenblat2025]. We will calculate the overall mean effect size and its 95%-confidence and prediction intervals for the different methods of calculating the effect sizes and compare their conclusions in regard to the original meta-analysis hypothesis by assessing whether the confidence and prediction intervals overlap with an effect size of zero.

Based on the findings from the review, the case study, and the informed imputation parameters, we will offer recommendations for calculating effect size measures in meta-analyses of exercise interventions.

### References
